---
title: "Produce_Single_AA_Percent_Composition.rmd"
author: "Matthew Curcio"
date: "March 22, 2019"
output: html_document
---

## Title: Produce_Single_AA_Percent_Composition.rmd

#### Summary: 

#### Libraries:
```{r libraries, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Libraries = c("readr", "stringr", "dplyr")

# Install if not present
for(p in Libraries){
    if(!require(p, character.only = TRUE))
        install.packages(p)
    library(p, character.only = TRUE)
}
```

#### Produce % AA Composition from linear polypeptides
```{r percent_aa}
linear_pp_to_percent_aa <- function(df) {
    col_titles = t(c("TotalAA", "G", 
                     "P", "A", "V", "L", "I",
                     "M", "C", "F", "Y", "W", 
                     "H", "K", "R", "Q", "N", 
                     "E", "D", "S", "T"))
    file_name <- paste("test_harness", "_paa.csv", sep = "")
    write.table(col_titles, 
                file_name,  
                sep = ",", 
                col.names = FALSE, 
                row.names = FALSE, 
                eol = "\n")
    aa_nums = as.vector(matrix(0, ncol = 21))
    ############################################
    for (row in seq(length(df))) {
        # First column is protein_class
        total_aa = nchar(df[1,row], keepNA = FALSE)
        aa_nums[1] = total_aa
        # Columns 2:21 - Calculate percent AA
        for (j in 3:22) {
            aa_nums[j] = str_count(df[1,row], col_titles[j]) / total_aa
        }
        aa_nums = t(aa_nums)
        # Write/append vector of AA values
        write(aa_nums, file = file_name, append = TRUE, ncolumns = 22, sep = ",")
    }
}
```

#### Create Class and ID columns
```{r}
code_key <- c("Ctrl", "Ery", "Hcy", "Hgb", "Hhe", "Lgb", "Mgb")

fill_vector <- function() {
    Class <- vector(mode = "character", length = 3500)
    ID <- vector(mode = "character", length = 3500)
    # Fill: Class & ID
    for (j in 1:500) {
        Class[j] = "Ctrl"
        ID[j] = paste("Ctrl", j, sep = "")
    }
    for (j in 501:1000) {
        Class[j] = "Ery"
        ID[j] = paste("Ery", j, sep = "")
    }
    for (j in 1001:1500) {
        Class[j] = "Hcy"
        ID[j] = paste("Hcy", j, sep = "")
    }
    for (j in 1501:2000) {
        Class[j] = "Hgb"
        ID[j] = paste("Hgb", j, sep = "")
    }
    for (j in 2001:2500) {
        Class[j] = "Hhe"
        ID[j] = paste("Hhe", j, sep = "")
    }
    for (j in 2501:3000) {
        Class[j] = "Lgb"
        ID[j] = paste("Lgb", j, sep = "")
    }
    for (j in 3001:3500) {
        Class[j] = "Mgb"
        ID[j] = paste("Mgb", j, sep = "")
    }
    return (cbind(Class,ID))
}

keeper = fill_vector()
```

#### READ in .lst for translation to Percent AA
```{r}
setwd("~/Dropbox/Oxy-RF/2B_Test_Harness/Test-Harness-2-PAA")

## File
file <- "7_class_500_test_harness_2019-03-22_12-33-09-AM.lst"
 
## Create connection
con <- file(description = file, "rt")
 
## Hopefully you know the number of lines from some other source or
com <- paste("wc -l ", file, " | awk '{ print $1 }'", sep = "")
n <- system(command = com, intern = TRUE)
 
## Loop over a file connection
for(i in 1:n) {
  tmp = readLines(con, 1) # Read one line 
  ## take linear polypeptide and transform to percent aa 
  linear_pp_to_percent_aa(tmp)
}

```


```{r}
start_time <- Sys.time() # Start timer

end_time <- Sys.time()   # End timer
end_time - start_time    # Display time
```
















Machine Settings:
```{r}
Sys.info()[c(1:3,5)]
```
```{r}
sessionInfo()
```
EOF