---
title: "Gen-500-Test-Harness.rmd"
author: "Matthew Curcio"
date: "March 7, 2019"
output: html_document
---

## Title: Gen-500-Test-Harness.rmd

#### Summary: 

Libraries:
```{r libraries, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Libraries = c("doMC")

# Install if not present
for(p in Libraries){
    if(!require(p, character.only = TRUE))
        install.packages(p)
    library(p, character.only = TRUE)
}
```


```{r file_loop}
setwd("/0_Data/aa-strings-data")

generate_500_test_harness_files <- function(){
    
    registerDoMC(cores = 3)
    prot_list <- list.files(pattern = ".txt$")
    
    for (i in length(prot_list)){
        # write header to empty test-harness file
        key_code <- sub("protein_class_(.*)\\.txt", "\\1", prot_list[i])
        key_file_name <- paste(key_code,
                               "_test_harness.lst",
                               sep = "")
        file_connect <- file(key_file_name)
        time_stamp <- as.POSIXlt(Sys.time())
        file_header <- paste(time_stamp, " ", key_file_name, sep = "")
        write(file_header, file_connect)
    
        # Generate index of 500
        line_count <- length(readLines(prot_list[i]))
        index <- sample.int(500, n = line_count, replace = TRUE)
    
        con <- file(prot_list[i], open = "r")
        con <- file(key_file_name, open = "w")
        
        # Choose 500 lines from protein_class files
        for (j in seq(1, 500)) {
            one_line <- read.table(prot_list[i],
                                   skip = index[j],
                                   header = FALSE)
            write.table(one_line, 
                        prot_list[1], 
                        append = T,
                        quote = F, 
                        eol = "\n", 
                        row.names = F,
                        col.names = F)
        }
    }
    }
```

```{r}
start_time <- Sys.time() # Start timer

generate_500_test_harness_files()

end_time <- Sys.time()   # End timer
end_time - start_time    # Display time
```


Machine Settings:
```{r}
Sys.info()[c(1:3,5)]
```
```{r}
sessionInfo()
```
EOF